#
# comando de inicio para odoo
#   docker compose exec -u root erp bash -c "install -d -o odoo -g odoo /var/lib/odoo/.local"
#

services:
  db:
    image: postgres:12.4
#    ports:
#      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=fehy5Hvdj7gD
      - POSTGRES_USER=sit_odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: "-c logging_collector=on -c max_connections=1000 -c log_lock_waits=on"
    volumes:
      - ./odoo-pgdata:/var/lib/postgresql/data/pgdata
  erp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8069:8069'
      - "8072:8072" # live chat
    restart: always
    volumes:
      - ./odoo-varlib:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
    environment:
      - ERP_DEBUG_MODE=True
      - ERP_LONGPOLLING_PORT=8072
      - ERP_DB_HOST=db
      - ERP_DB_PORT=5432
      - ERP_DB_USER=sit_odoo
      - ERP_DB_PASSWORD=fehy5Hvdj7gD
      - ERP_LIMIT_TIME_CPU=5600
      - ERP_LIMIT_TIME_REAL=7200
      - ERP_PROXY_MODE=True
      - ERP_WORKERS=4
      # - ERP_DBFILTER=viniteca_tk1
      # - ERP_BUS_ENABLE=True
      # - ERP_BUS_URL=http://localhost:8069
      - ERP_ADMIN_PASSWD=suPer-TKs3creT-paSs
      - ERP_ADDONS_PATH=/mnt/extra-addons
    networks:
      default:
      net-web:
        aliases:
        - atom-db
        ipv4_address: 192.168.231.101
networks:
  default:
    external: false
  net-web:
    name: network-web
    external: false
